SET client_encoding = 'UTF8';
DROP TABLE IF EXISTS Asignacion CASCADE;
DROP TABLE IF EXISTS Vehiculo CASCADE;
DROP TABLE IF EXISTS Materia CASCADE;
DROP TABLE IF EXISTS Docente CASCADE;
DROP TABLE IF EXISTS Carrera CASCADE;
CREATE TABLE Carrera (carrera_id INT PRIMARY KEY, nombre VARCHAR(100), siglas VARCHAR(10));
CREATE TABLE Docente (docente_id SERIAL PRIMARY KEY, nombre VARCHAR(255) NOT NULL, rfc VARCHAR(50) DEFAULT 'S/N', grado VARCHAR(50) DEFAULT 'SD', condicion VARCHAR(50) DEFAULT 'Personal Civil', genero VARCHAR(50), domicilio TEXT, credencial_ine VARCHAR(100), estado_evaluacion VARCHAR(50) DEFAULT 'Pendiente');
CREATE TABLE Materia (materia_id SERIAL PRIMARY KEY, nombre VARCHAR(255) NOT NULL, carrera_id INT REFERENCES Carrera(carrera_id));
CREATE TABLE Vehiculo (vehiculo_id SERIAL PRIMARY KEY, docente_id INT REFERENCES Docente(docente_id), placas VARCHAR(20), marca VARCHAR(50), modelo VARCHAR(50));
CREATE TABLE Asignacion (asignacion_id SERIAL PRIMARY KEY, docente_id INT REFERENCES Docente(docente_id), materia_id INT REFERENCES Materia(materia_id), horas INT DEFAULT 0);
INSERT INTO Carrera (carrera_id, nombre, siglas) VALUES (1, 'IngenierÃ­a en ComputaciÃ³n e InformÃ¡tica', 'ICI');
INSERT INTO Carrera (carrera_id, nombre, siglas) VALUES (2, 'IngenierÃ­a en Comunicaciones y ElectrÃ³nica', 'ICE');
INSERT INTO Carrera (carrera_id, nombre, siglas) VALUES (3, 'IngenierÃ­a Industrial', 'II');
INSERT INTO Carrera (carrera_id, nombre, siglas) VALUES (4, 'IngenierÃ­a en ConstrucciÃ³n', 'IC');
INSERT INTO Carrera (carrera_id, nombre, siglas) VALUES (5, 'Tronco ComÃºn', 'TC');
INSERT INTO Materia (nombre, carrera_id) VALUES ('Historia Militar de México Independiente', 5);
INSERT INTO Docente (nombre) VALUES ('Mónica Adriana Santos Sánchez');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Mónica Adriana Santos Sánchez' AND m.nombre = 'Historia Militar de México Independiente' AND m.carrera_id = 5 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Técnicas de Aprendizaje', 5);
INSERT INTO Docente (nombre) VALUES ('Ana Laura Espinosa Castillo');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Ana Laura Espinosa Castillo' AND m.nombre = 'Técnicas de Aprendizaje' AND m.carrera_id = 5 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Expresión Oral y Escrita', 5);
INSERT INTO Docente (nombre) VALUES ('Nancy Georgina Barrueta Guerra');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Nancy Georgina Barrueta Guerra' AND m.nombre = 'Expresión Oral y Escrita' AND m.carrera_id = 5 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Química General', 5);
INSERT INTO Docente (nombre) VALUES ('Sandra Jocelyn Garrido Mijangos');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Sandra Jocelyn Garrido Mijangos' AND m.nombre = 'Química General' AND m.carrera_id = 5 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Física General', 5);
INSERT INTO Docente (nombre) VALUES ('Jerry Nathan Reider Burstin');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Jerry Nathan Reider Burstin' AND m.nombre = 'Física General' AND m.carrera_id = 5 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Matemáticas Básicas para Ingeniería', 5);
INSERT INTO Docente (nombre) VALUES ('Fátima Virginia Serrano Muñoz');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Fátima Virginia Serrano Muñoz' AND m.nombre = 'Matemáticas Básicas para Ingeniería' AND m.carrera_id = 5 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Geometría Analítica', 5);
INSERT INTO Docente (nombre) VALUES ('Edmanuel Rangel de la Cruz');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Edmanuel Rangel de la Cruz' AND m.nombre = 'Geometría Analítica' AND m.carrera_id = 5 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Cálculo Diferencial', 5);
INSERT INTO Docente (nombre) VALUES ('Wendy Coronel Ramírez');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Wendy Coronel Ramírez' AND m.nombre = 'Cálculo Diferencial' AND m.carrera_id = 5 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Desarrollo Humano', 5);
INSERT INTO Docente (nombre) VALUES ('Karla Minerva Donath Pétriz');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Karla Minerva Donath Pétriz' AND m.nombre = 'Desarrollo Humano' AND m.carrera_id = 5 LIMIT 1;
INSERT INTO Docente (nombre) VALUES ('Antonio Aguilar Razo');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Antonio Aguilar Razo' AND m.nombre = 'Historia Militar de México Independiente' AND m.carrera_id = 5 LIMIT 1;
INSERT INTO Docente (nombre) VALUES ('Rafael Juárez Vargas');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Rafael Juárez Vargas' AND m.nombre = 'Química General' AND m.carrera_id = 5 LIMIT 1;
INSERT INTO Docente (nombre) VALUES ('Diego Alfaro Manjarrez');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Diego Alfaro Manjarrez' AND m.nombre = 'Física General' AND m.carrera_id = 5 LIMIT 1;
INSERT INTO Docente (nombre) VALUES ('Raúl González Alcaráz');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Raúl González Alcaráz' AND m.nombre = 'Cálculo Diferencial' AND m.carrera_id = 5 LIMIT 1;
INSERT INTO Docente (nombre) VALUES ('Enrique Rivera Medina');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Enrique Rivera Medina' AND m.nombre = 'Matemáticas Básicas para Ingeniería' AND m.carrera_id = 5 LIMIT 1;
INSERT INTO Docente (nombre) VALUES ('Jorge Alberto Gómez García');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Jorge Alberto Gómez García' AND m.nombre = 'Cálculo Diferencial' AND m.carrera_id = 5 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Enrique Rivera Medina' AND m.nombre = 'Geometría Analítica' AND m.carrera_id = 5 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Idioma Extranjero VII', 5);
INSERT INTO Docente (nombre) VALUES ('Gilda Terán Ramírez');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Gilda Terán Ramírez' AND m.nombre = 'Idioma Extranjero VII' AND m.carrera_id = 5 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Idioma Extranjero V', 5);
INSERT INTO Docente (nombre) VALUES ('Daniela Peña Gil');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Daniela Peña Gil' AND m.nombre = 'Idioma Extranjero V' AND m.carrera_id = 5 LIMIT 1;
INSERT INTO Docente (nombre) VALUES ('María del Carmen Román Sierra');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'María del Carmen Román Sierra' AND m.nombre = 'Idioma Extranjero V' AND m.carrera_id = 5 LIMIT 1;
INSERT INTO Docente (nombre) VALUES ('María Edna Días Salas');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'María Edna Días Salas' AND m.nombre = 'Idioma Extranjero VII' AND m.carrera_id = 5 LIMIT 1;
INSERT INTO Docente (nombre) VALUES ('Linda Elvira Lara Cerda');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Linda Elvira Lara Cerda' AND m.nombre = 'Idioma Extranjero V' AND m.carrera_id = 5 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Idioma Extranjero III', 5);
INSERT INTO Docente (nombre) VALUES ('Diana Guadalupe Godínez García');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Diana Guadalupe Godínez García' AND m.nombre = 'Idioma Extranjero III' AND m.carrera_id = 5 LIMIT 1;
INSERT INTO Docente (nombre) VALUES ('Victoria Azucena Manzo Pérez');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Victoria Azucena Manzo Pérez' AND m.nombre = 'Idioma Extranjero VII' AND m.carrera_id = 5 LIMIT 1;
INSERT INTO Docente (nombre) VALUES ('Daniel Hernández García');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Daniel Hernández García' AND m.nombre = 'Idioma Extranjero V' AND m.carrera_id = 5 LIMIT 1;
INSERT INTO Docente (nombre) VALUES ('Ixchel Janetzy Bermejo Haro');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Ixchel Janetzy Bermejo Haro' AND m.nombre = 'Idioma Extranjero III' AND m.carrera_id = 5 LIMIT 1;
INSERT INTO Docente (nombre) VALUES ('Carlos Eduardo Garay Romero');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Carlos Eduardo Garay Romero' AND m.nombre = 'Idioma Extranjero VII' AND m.carrera_id = 5 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Idioma extranjero I', 5);
INSERT INTO Docente (nombre) VALUES ('Rosa Irais Cruz Mendoza');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Rosa Irais Cruz Mendoza' AND m.nombre = 'Idioma extranjero I' AND m.carrera_id = 5 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Remedial de Inglés', 5);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Karla Minerva Donath Pétriz' AND m.nombre = 'Remedial de Inglés' AND m.carrera_id = 5 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'María Edna Días Salas' AND m.nombre = 'Remedial de Inglés' AND m.carrera_id = 5 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Derechos Humanos', 1);
INSERT INTO Docente (nombre) VALUES ('Leslie Denyss García García');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Leslie Denyss García García' AND m.nombre = 'Derechos Humanos' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Proyectos de ingeniería', 1);
INSERT INTO Docente (nombre) VALUES ('Gabriel Torres Pantaleón');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Gabriel Torres Pantaleón' AND m.nombre = 'Proyectos de ingeniería' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Seminario de tesis I', 1);
INSERT INTO Docente (nombre) VALUES ('David Gerardo Plaza Herrera');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'David Gerardo Plaza Herrera' AND m.nombre = 'Seminario de tesis I' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Explosivos y demoliciones', 1);
INSERT INTO Docente (nombre) VALUES ('Carlos Barragán Zavaleta');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Carlos Barragán Zavaleta' AND m.nombre = 'Explosivos y demoliciones' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Ingeniería de ríos y costas', 1);
INSERT INTO Docente (nombre) VALUES ('Jorge Luis Oliver González');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Jorge Luis Oliver González' AND m.nombre = 'Ingeniería de ríos y costas' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Sistemas de transportes I', 1);
INSERT INTO Docente (nombre) VALUES ('Anahí Jessica Chávez Ávila');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Anahí Jessica Chávez Ávila' AND m.nombre = 'Sistemas de transportes I' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Estructuras metálicas', 1);
INSERT INTO Docente (nombre) VALUES ('Daniel Herrera Gallo');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Daniel Herrera Gallo' AND m.nombre = 'Estructuras metálicas' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Obras hidráulicas', 1);
INSERT INTO Docente (nombre) VALUES ('Juan José Lozano Bermúdez');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Juan José Lozano Bermúdez' AND m.nombre = 'Obras hidráulicas' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Desarrollo Humano', 1);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Leslie Denyss García García' AND m.nombre = 'Desarrollo Humano' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Leslie Denyss García García' AND m.nombre = 'Derechos Humanos' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Gabriel Torres Pantaleón' AND m.nombre = 'Proyectos de ingeniería' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'David Gerardo Plaza Herrera' AND m.nombre = 'Seminario de tesis I' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Carlos Barragán Zavaleta' AND m.nombre = 'Explosivos y demoliciones' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Jorge Luis Oliver González' AND m.nombre = 'Ingeniería de ríos y costas' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Anahí Jessica Chávez Ávila' AND m.nombre = 'Sistemas de transportes I' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Docente (nombre) VALUES ('Jesús Irving Cadena Pérez');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Jesús Irving Cadena Pérez' AND m.nombre = 'Estructuras metálicas' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Juan José Lozano Bermúdez' AND m.nombre = 'Obras hidráulicas' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Leslie Denyss García García' AND m.nombre = 'Desarrollo Humano' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Adiestramiento militar y capacitación docente I', 1);
INSERT INTO Docente (nombre) VALUES ('Juan Manuel Mozo Spezia');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Juan Manuel Mozo Spezia' AND m.nombre = 'Adiestramiento militar y capacitación docente I' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Aspectos  administrativos del mando', 1);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Juan Manuel Mozo Spezia' AND m.nombre = 'Aspectos  administrativos del mando' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Dinámica estructural', 1);
INSERT INTO Docente (nombre) VALUES ('José Rodolfo Gutiérrez Villagrán');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'José Rodolfo Gutiérrez Villagrán' AND m.nombre = 'Dinámica estructural' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Estructuras de mampostería', 1);
INSERT INTO Docente (nombre) VALUES ('Daniel Antonio Martínez Villela');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Daniel Antonio Martínez Villela' AND m.nombre = 'Estructuras de mampostería' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Mecánica de suelos II', 1);
INSERT INTO Docente (nombre) VALUES ('Luis Iván Juárez Rodarte');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Luis Iván Juárez Rodarte' AND m.nombre = 'Mecánica de suelos II' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Diseño de estructuras de concreto I', 1);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Daniel Antonio Martínez Villela' AND m.nombre = 'Diseño de estructuras de concreto I' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Alcantarillado', 1);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Juan José Lozano Bermúdez' AND m.nombre = 'Alcantarillado' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Administración de obras I', 1);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Ana Laura Espinosa Castillo' AND m.nombre = 'Administración de obras I' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Introducción a la ingeniería ambiental', 1);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Anahí Jessica Chávez Ávila' AND m.nombre = 'Introducción a la ingeniería ambiental' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Leslie Denyss García García' AND m.nombre = 'Desarrollo Humano' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Juan Manuel Mozo Spezia' AND m.nombre = 'Adiestramiento militar y capacitación docente I' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Juan Manuel Mozo Spezia' AND m.nombre = 'Aspectos  administrativos del mando' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'José Rodolfo Gutiérrez Villagrán' AND m.nombre = 'Dinámica estructural' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Daniel Antonio Martínez Villela' AND m.nombre = 'Estructuras de mampostería' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Luis Iván Juárez Rodarte' AND m.nombre = 'Mecánica de suelos II' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Daniel Antonio Martínez Villela' AND m.nombre = 'Diseño de estructuras de concreto I' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Juan José Lozano Bermúdez' AND m.nombre = 'Alcantarillado' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Ana Laura Espinosa Castillo' AND m.nombre = 'Administración de obras I' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Anahí Jessica Chávez Ávila' AND m.nombre = 'Introducción a la ingeniería ambiental' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Leslie Denyss García García' AND m.nombre = 'Desarrollo Humano' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Investigación de Operaciones', 1);
INSERT INTO Docente (nombre) VALUES ('María de Lourdes Léyva Dávila');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'María de Lourdes Léyva Dávila' AND m.nombre = 'Investigación de Operaciones' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Fotogrametría', 1);
INSERT INTO Docente (nombre) VALUES ('Norma Ponce Rodríguez');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Norma Ponce Rodríguez' AND m.nombre = 'Fotogrametría' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Geología', 1);
INSERT INTO Docente (nombre) VALUES ('María del Mar Almazán López');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'María del Mar Almazán López' AND m.nombre = 'Geología' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Análisis de Elemento Estructurales II', 1);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Daniel Herrera Gallo' AND m.nombre = 'Análisis de Elemento Estructurales II' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Hidráulica I', 1);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Jorge Luis Oliver González' AND m.nombre = 'Hidráulica I' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Procedimientos de Construcción', 1);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Carlos Barragán Zavaleta' AND m.nombre = 'Procedimientos de Construcción' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Sistemas y Control de Calidad', 1);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Fátima Virginia Serrano Muñoz' AND m.nombre = 'Sistemas y Control de Calidad' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Leslie Denyss García García' AND m.nombre = 'Desarrollo Humano' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'María de Lourdes Léyva Dávila' AND m.nombre = 'Investigación de Operaciones' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Norma Ponce Rodríguez' AND m.nombre = 'Fotogrametría' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'María del Mar Almazán López' AND m.nombre = 'Geología' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Docente (nombre) VALUES ('Alberto Emanuel Aguilar Avendaño');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Alberto Emanuel Aguilar Avendaño' AND m.nombre = 'Análisis de Elemento Estructurales II' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Jorge Luis Oliver González' AND m.nombre = 'Hidráulica I' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Carlos Barragán Zavaleta' AND m.nombre = 'Procedimientos de Construcción' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Fátima Virginia Serrano Muñoz' AND m.nombre = 'Sistemas y Control de Calidad' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Leslie Denyss García García' AND m.nombre = 'Desarrollo Humano' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Filosofía', 4);
INSERT INTO Docente (nombre) VALUES ('Luisa Fernanda Rojas Paz');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Luisa Fernanda Rojas Paz' AND m.nombre = 'Filosofía' AND m.carrera_id = 4 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Probabilidad y estadística', 4);
INSERT INTO Docente (nombre) VALUES ('Amparo Isabeth Villa García');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Amparo Isabeth Villa García' AND m.nombre = 'Probabilidad y estadística' AND m.carrera_id = 4 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Ecuaciones diferenciales', 4);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Diego Alfaro Manjarrez' AND m.nombre = 'Ecuaciones diferenciales' AND m.carrera_id = 4 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Cálculo vectorial II', 4);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Wendy Coronel Ramírez' AND m.nombre = 'Cálculo vectorial II' AND m.carrera_id = 4 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Electricidad y Magnetismo', 4);
INSERT INTO Docente (nombre) VALUES ('Yared Estephany Padilla Salmerón');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Yared Estephany Padilla Salmerón' AND m.nombre = 'Electricidad y Magnetismo' AND m.carrera_id = 4 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Mecánica II', 4);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'José Rodolfo Gutiérrez Villagrán' AND m.nombre = 'Mecánica II' AND m.carrera_id = 4 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Topografía I', 4);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Norma Ponce Rodríguez' AND m.nombre = 'Topografía I' AND m.carrera_id = 4 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Estructuras isostáticas', 4);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Alberto Emanuel Aguilar Avendaño' AND m.nombre = 'Estructuras isostáticas' AND m.carrera_id = 4 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Desarrollo Humano', 4);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Leslie Denyss García García' AND m.nombre = 'Desarrollo Humano' AND m.carrera_id = 4 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Explosivos', 3);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Gabriel Torres Pantaleón' AND m.nombre = 'Explosivos' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Protección de Sistemas Eléctricos', 3);
INSERT INTO Docente (nombre) VALUES ('Pablo Ortiz Mondragón');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Pablo Ortiz Mondragón' AND m.nombre = 'Protección de Sistemas Eléctricos' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Electrónica Analógica', 3);
INSERT INTO Docente (nombre) VALUES ('José Dario Betanzos Ramírez');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'José Dario Betanzos Ramírez' AND m.nombre = 'Electrónica Analógica' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Laboratorio de Sistemas Eléctricos de Potencia', 3);
INSERT INTO Docente (nombre) VALUES ('Albino Arteaga Escamilla');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Albino Arteaga Escamilla' AND m.nombre = 'Laboratorio de Sistemas Eléctricos de Potencia' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Iluminación', 3);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Jerry Nathan Reider Burstin' AND m.nombre = 'Iluminación' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Planeación y Control de la Producción', 3);
INSERT INTO Docente (nombre) VALUES ('Laura Avilés Ortiz');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Laura Avilés Ortiz' AND m.nombre = 'Planeación y Control de la Producción' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Ingeniería Económica', 3);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'María de Lourdes Léyva Dávila' AND m.nombre = 'Ingeniería Económica' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Seminario de Tesis I', 3);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Laura Avilés Ortiz' AND m.nombre = 'Seminario de Tesis I' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Derechos Humanos', 3);
INSERT INTO Docente (nombre) VALUES ('Jesica Nayeli Montoya Paz');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Jesica Nayeli Montoya Paz' AND m.nombre = 'Derechos Humanos' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Desarrollo Humano', 3);
INSERT INTO Docente (nombre) VALUES ('Karla Minerva Donath Petriz');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Karla Minerva Donath Petriz' AND m.nombre = 'Desarrollo Humano' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Adiestramiento Militar y Capacitación Docente I', 3);
INSERT INTO Docente (nombre) VALUES ('Raymundo Cruz Alarcón');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Raymundo Cruz Alarcón' AND m.nombre = 'Adiestramiento Militar y Capacitación Docente I' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Procesos de Manufactura', 3);
INSERT INTO Docente (nombre) VALUES ('Usiel Sandino Silva Rivera');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Usiel Sandino Silva Rivera' AND m.nombre = 'Procesos de Manufactura' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Control Digital', 3);
INSERT INTO Docente (nombre) VALUES ('Arturo Enrique Gil García');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Arturo Enrique Gil García' AND m.nombre = 'Control Digital' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Electrónica Digital', 3);
INSERT INTO Docente (nombre) VALUES ('Valentín Nájera Bello');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Valentín Nájera Bello' AND m.nombre = 'Electrónica Digital' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Instalaciones Eléctricas II', 3);
INSERT INTO Docente (nombre) VALUES ('Fabiola Vázquez Hernández');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Fabiola Vázquez Hernández' AND m.nombre = 'Instalaciones Eléctricas II' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Subestaciones Eléctricas', 3);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Pablo Ortiz Mondragón' AND m.nombre = 'Subestaciones Eléctricas' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Ingeniería de Métodos y Medición del Trabajo', 3);
INSERT INTO Docente (nombre) VALUES ('Sergio Rafael García Bravo');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Sergio Rafael García Bravo' AND m.nombre = 'Ingeniería de Métodos y Medición del Trabajo' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Costos Aplicados a la Ingeniería', 3);
INSERT INTO Docente (nombre) VALUES ('Ricardo Alejandro Juárez Ruiz');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Ricardo Alejandro Juárez Ruiz' AND m.nombre = 'Costos Aplicados a la Ingeniería' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Ingeniería Ambiental', 3);
INSERT INTO Docente (nombre) VALUES ('German Dimitriv Jojoa Unigarro');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'German Dimitriv Jojoa Unigarro' AND m.nombre = 'Ingeniería Ambiental' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Karla Minerva Donath Petriz' AND m.nombre = 'Desarrollo Humano' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Dinámica de Sistemas Físicos', 3);
INSERT INTO Docente (nombre) VALUES ('José Luis Flores Silva');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'José Luis Flores Silva' AND m.nombre = 'Dinámica de Sistemas Físicos' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Termodinámica Aplicada', 3);
INSERT INTO Docente (nombre) VALUES ('Adán Juárez Motalvo');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Adán Juárez Motalvo' AND m.nombre = 'Termodinámica Aplicada' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Investigación de Operaciones I', 3);
INSERT INTO Docente (nombre) VALUES ('Alejandra Melina Mil Martinez');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Alejandra Melina Mil Martinez' AND m.nombre = 'Investigación de Operaciones I' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Circuitos Lógicos', 3);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Arturo Enrique Gil García' AND m.nombre = 'Circuitos Lógicos' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Dispositivos Electrónicos', 3);
INSERT INTO Docente (nombre) VALUES ('Jorge Antonio Morales Sierra');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Jorge Antonio Morales Sierra' AND m.nombre = 'Dispositivos Electrónicos' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Análisis de Circuitos Eléctricos II', 3);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Valentín Nájera Bello' AND m.nombre = 'Análisis de Circuitos Eléctricos II' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Mecánica de Fluidos', 3);
INSERT INTO Docente (nombre) VALUES ('Rubén Mil Martínez');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Rubén Mil Martínez' AND m.nombre = 'Mecánica de Fluidos' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Cultura de la Calidad', 3);
INSERT INTO Docente (nombre) VALUES ('Zenón Rodríguez Arriero');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Zenón Rodríguez Arriero' AND m.nombre = 'Cultura de la Calidad' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Karla Minerva Donath Petriz' AND m.nombre = 'Desarrollo Humano' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Electricidad y Magnetismo', 3);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Yared Estephany Padilla Salmerón' AND m.nombre = 'Electricidad y Magnetismo' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Probabilidad y Estadística', 3);
INSERT INTO Docente (nombre) VALUES ('Isidro Morales García');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Isidro Morales García' AND m.nombre = 'Probabilidad y Estadística' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Ecuaciones Diferenciales', 3);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'José Luis Flores Silva' AND m.nombre = 'Ecuaciones Diferenciales' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Cálculo Vectorial II', 3);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Isidro Morales García' AND m.nombre = 'Cálculo Vectorial II' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Tecnología de los Materiales', 3);
INSERT INTO Docente (nombre) VALUES ('Raúl Efren Del Villar Brown');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Raúl Efren Del Villar Brown' AND m.nombre = 'Tecnología de los Materiales' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Filosofía', 3);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Luisa Fernanda Rojas Paz' AND m.nombre = 'Filosofía' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Docente (nombre) VALUES ('Maria Antonieta Valencia Castro');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Maria Antonieta Valencia Castro' AND m.nombre = 'Desarrollo Humano' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Gabriel Torres Pantaleón' AND m.nombre = 'Explosivos' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Diseño Herramental', 3);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Usiel Sandino Silva Rivera' AND m.nombre = 'Diseño Herramental' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Instrumentación y Control', 3);
INSERT INTO Docente (nombre) VALUES ('Jaime Cruz Cruz');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Jaime Cruz Cruz' AND m.nombre = 'Instrumentación y Control' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Laura Avilés Ortiz' AND m.nombre = 'Planeación y Control de la Producción' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Sergio Rafael García Bravo' AND m.nombre = 'Ingeniería Económica' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Nancy Georgina Barrueta Guerra' AND m.nombre = 'Seminario de Tesis I' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Procesos de Manufactura II', 3);
INSERT INTO Docente (nombre) VALUES ('Israel Barragán Santiago');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Israel Barragán Santiago' AND m.nombre = 'Procesos de Manufactura II' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Instalaciones Electromecánicas', 3);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Yared Estephany Padilla Salmerón' AND m.nombre = 'Instalaciones Electromecánicas' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Jesica Nayeli Montoya Paz' AND m.nombre = 'Derechos Humanos' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Raymundo Cruz Alarcón' AND m.nombre = 'Desarrollo Humano' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Raymundo Cruz Alarcón' AND m.nombre = 'Adiestramiento Militar y Capacitación Docente I' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Diseño y Selección de Elementos de Maquinas', 3);
INSERT INTO Docente (nombre) VALUES ('Gabriel Gutiérrez Díaz');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Gabriel Gutiérrez Díaz' AND m.nombre = 'Diseño y Selección de Elementos de Maquinas' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Máquinas de Desplazamiento Positivo', 3);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Rubén Mil Martínez' AND m.nombre = 'Máquinas de Desplazamiento Positivo' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Procesos de Manufactura I', 3);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Usiel Sandino Silva Rivera' AND m.nombre = 'Procesos de Manufactura I' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Tratamientos Térmicos', 3);
INSERT INTO Docente (nombre) VALUES ('José Guadalupe Morales Mendez');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'José Guadalupe Morales Mendez' AND m.nombre = 'Tratamientos Térmicos' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Turbomáquinas', 3);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Jaime Cruz Cruz' AND m.nombre = 'Turbomáquinas' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Fabiola Vázquez Hernández' AND m.nombre = 'Ingeniería de Métodos y Medición del Trabajo' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Docente (nombre) VALUES ('Zaira Gutiérrez Pérez');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Zaira Gutiérrez Pérez' AND m.nombre = 'Costos Aplicados a la Ingeniería' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'German Dimitriv Jojoa Unigarro' AND m.nombre = 'Ingeniería Ambiental' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Luisa Fernanda Rojas Paz' AND m.nombre = 'Desarrollo Humano' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Análisis Dinámico de Maquinaria', 3);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Gabriel Gutiérrez Díaz' AND m.nombre = 'Análisis Dinámico de Maquinaria' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Docente (nombre) VALUES ('Juana Ofelia Juarez Carrillo');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Juana Ofelia Juarez Carrillo' AND m.nombre = 'Termodinámica Aplicada' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Rubén Mil Martínez' AND m.nombre = 'Mecánica de Fluidos' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'María de Lourdes Léyva Dávila' AND m.nombre = 'Investigación de Operaciones I' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Resistencia de Materiales II', 3);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'José Guadalupe Morales Mendez' AND m.nombre = 'Resistencia de Materiales II' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Tecnología de los Materiales I', 3);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Raúl Efren Del Villar Brown' AND m.nombre = 'Tecnología de los Materiales I' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Zenón Rodríguez Arriero' AND m.nombre = 'Cultura de la Calidad' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Luisa Fernanda Rojas Paz' AND m.nombre = 'Desarrollo Humano' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Raymundo Cruz Alarcón' AND m.nombre = 'Adiestramiento Militar y Capacitación Docente I' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Electroquímica y Laboratorio', 3);
INSERT INTO Docente (nombre) VALUES ('Omar Hernández Montes');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Omar Hernández Montes' AND m.nombre = 'Electroquímica y Laboratorio' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Docente (nombre) VALUES ('Karina Cruz Hernández');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Karina Cruz Hernández' AND m.nombre = 'Procesos de Manufactura' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Operaciones Unitarias I y Laboratorio', 3);
INSERT INTO Docente (nombre) VALUES ('Perla Xochitl Sotelo Navarro');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Perla Xochitl Sotelo Navarro' AND m.nombre = 'Operaciones Unitarias I y Laboratorio' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Operaciones de Transferencia de Calor y Laboratorio', 3);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Adán Juárez Motalvo' AND m.nombre = 'Operaciones de Transferencia de Calor y Laboratorio' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Zaira Gutiérrez Pérez' AND m.nombre = 'Costos Aplicados a la Ingeniería' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Docente (nombre) VALUES ('Claudia Mercedes Cortesia de Peña');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Claudia Mercedes Cortesia de Peña' AND m.nombre = 'Ingeniería de Métodos y Medición del Trabajo' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Docente (nombre) VALUES ('Gloria Anahí Valencia Luna');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Gloria Anahí Valencia Luna' AND m.nombre = 'Ingeniería Ambiental' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Raymundo Cruz Alarcón' AND m.nombre = 'Desarrollo Humano' AND m.carrera_id = 3 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Laboratorio de ingeniería de control', 2);
INSERT INTO Docente (nombre) VALUES ('Miguel Ángel Borja Benítez');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Miguel Ángel Borja Benítez' AND m.nombre = 'Laboratorio de ingeniería de control' AND m.carrera_id = 2 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Inteligencia artificial', 2);
INSERT INTO Docente (nombre) VALUES ('José Portillo Portillo');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'José Portillo Portillo' AND m.nombre = 'Inteligencia artificial' AND m.carrera_id = 2 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Laboratorio de sistemas digitales', 2);
INSERT INTO Docente (nombre) VALUES ('José Alberto Balderas Castillo');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'José Alberto Balderas Castillo' AND m.nombre = 'Laboratorio de sistemas digitales' AND m.carrera_id = 2 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Ingeniería de redes II', 2);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Miguel Ángel Borja Benítez' AND m.nombre = 'Ingeniería de redes II' AND m.carrera_id = 2 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Conversión de la energía II', 2);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Karina Cruz Hernández' AND m.nombre = 'Conversión de la energía II' AND m.carrera_id = 2 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Telefonía', 2);
INSERT INTO Docente (nombre) VALUES ('Luis Alberto Vázquez Toledo');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Luis Alberto Vázquez Toledo' AND m.nombre = 'Telefonía' AND m.carrera_id = 2 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Comunicaciones por microondas', 2);
INSERT INTO Docente (nombre) VALUES ('Enrique Valaguez Velázquez');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Enrique Valaguez Velázquez' AND m.nombre = 'Comunicaciones por microondas' AND m.carrera_id = 2 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Seminario de tesis I', 2);
INSERT INTO Docente (nombre) VALUES ('Juan Carlos Álvarez Zeferino');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Juan Carlos Álvarez Zeferino' AND m.nombre = 'Seminario de tesis I' AND m.carrera_id = 2 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Derechos Humanos', 2);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Jesica Nayeli Montoya Paz' AND m.nombre = 'Derechos Humanos' AND m.carrera_id = 2 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Desarrollo Humano', 2);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Maria Antonieta Valencia Castro' AND m.nombre = 'Desarrollo Humano' AND m.carrera_id = 2 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Adiestramiento militar y capacitación docente I', 2);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Raymundo Cruz Alarcón' AND m.nombre = 'Adiestramiento militar y capacitación docente I' AND m.carrera_id = 2 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Control analógico', 2);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Jorge Alberto Gómez García' AND m.nombre = 'Control analógico' AND m.carrera_id = 2 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Circuitos integrados analógicos', 2);
INSERT INTO Docente (nombre) VALUES ('José Mauricio Rodríguez Sánchez');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'José Mauricio Rodríguez Sánchez' AND m.nombre = 'Circuitos integrados analógicos' AND m.carrera_id = 2 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Ingeniería de redes I', 2);
INSERT INTO Docente (nombre) VALUES ('Enrique De Gyves Dominguez');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Enrique De Gyves Dominguez' AND m.nombre = 'Ingeniería de redes I' AND m.carrera_id = 2 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Líneas de transmisión y guías de onda', 2);
INSERT INTO Docente (nombre) VALUES ('Sergio Peña Ruiz');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Sergio Peña Ruiz' AND m.nombre = 'Líneas de transmisión y guías de onda' AND m.carrera_id = 2 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Ingeniería acústica II', 2);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Zaira Gutiérrez Pérez' AND m.nombre = 'Ingeniería acústica II' AND m.carrera_id = 2 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Sistemas de comunicaciones', 2);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Luis Alberto Vázquez Toledo' AND m.nombre = 'Sistemas de comunicaciones' AND m.carrera_id = 2 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Costos aplicados a la ingeniería', 2);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Ricardo Alejandro Juárez Ruiz' AND m.nombre = 'Costos aplicados a la ingeniería' AND m.carrera_id = 2 LIMIT 1;
INSERT INTO Docente (nombre) VALUES ('María Esther Jiménez  Becerra');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'María Esther Jiménez  Becerra' AND m.nombre = 'Desarrollo Humano' AND m.carrera_id = 2 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Investigación de Operaciones', 2);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Claudia Mercedes Cortesia de Peña' AND m.nombre = 'Investigación de Operaciones' AND m.carrera_id = 2 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Electrónica I', 2);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'José Mauricio Rodríguez Sánchez' AND m.nombre = 'Electrónica I' AND m.carrera_id = 2 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Sistemas Digitales I', 2);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'José Alberto Balderas Castillo' AND m.nombre = 'Sistemas Digitales I' AND m.carrera_id = 2 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Análisis de Circuitos Eléctricos II', 2);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Valentín Nájera Bello' AND m.nombre = 'Análisis de Circuitos Eléctricos II' AND m.carrera_id = 2 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Señales y Sistemas I', 2);
INSERT INTO Docente (nombre) VALUES ('Berenice Borja Benítez');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Berenice Borja Benítez' AND m.nombre = 'Señales y Sistemas I' AND m.carrera_id = 2 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Cultura de la Calidad', 2);
INSERT INTO Docente (nombre) VALUES ('Juan David Ramírez Durán');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Juan David Ramírez Durán' AND m.nombre = 'Cultura de la Calidad' AND m.carrera_id = 2 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Impacto Ambiental', 2);
INSERT INTO Docente (nombre) VALUES ('Alberto Eduardo Flores Espinosa');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Alberto Eduardo Flores Espinosa' AND m.nombre = 'Impacto Ambiental' AND m.carrera_id = 2 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Termodinámica', 2);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Juana Ofelia Juarez Carrillo' AND m.nombre = 'Termodinámica' AND m.carrera_id = 2 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'María Esther Jiménez  Becerra' AND m.nombre = 'Desarrollo Humano' AND m.carrera_id = 2 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Filosofía', 2);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Luisa Fernanda Rojas Paz' AND m.nombre = 'Filosofía' AND m.carrera_id = 2 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Probabilidad y Estadística', 2);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Isidro Morales García' AND m.nombre = 'Probabilidad y Estadística' AND m.carrera_id = 2 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Ecuaciones Diferenciales', 2);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'José Luis Flores Silva' AND m.nombre = 'Ecuaciones Diferenciales' AND m.carrera_id = 2 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Cálculo Vectorial II', 2);
INSERT INTO Docente (nombre) VALUES ('María Felicia Jiménez Lavié');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'María Felicia Jiménez Lavié' AND m.nombre = 'Cálculo Vectorial II' AND m.carrera_id = 2 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Electricidad y Magnetismo', 2);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Albino Arteaga Escamilla' AND m.nombre = 'Electricidad y Magnetismo' AND m.carrera_id = 2 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Programación Avanzada', 2);
INSERT INTO Docente (nombre) VALUES ('Cristal Karina Galindo Duran');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Cristal Karina Galindo Duran' AND m.nombre = 'Programación Avanzada' AND m.carrera_id = 2 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Cinemática', 2);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Sergio Peña Ruiz' AND m.nombre = 'Cinemática' AND m.carrera_id = 2 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'María Esther Jiménez  Becerra' AND m.nombre = 'Desarrollo Humano' AND m.carrera_id = 2 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Jesica Nayeli Montoya Paz' AND m.nombre = 'Derechos Humanos' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Docente (nombre) VALUES ('María Teresa Parra Velasco');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'María Teresa Parra Velasco' AND m.nombre = 'Proyectos de Ingeniería' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'David Gerardo Plaza Herrera' AND m.nombre = 'Seminario de Tesis I' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Tecnologías de Información Emergente', 1);
INSERT INTO Docente (nombre) VALUES ('Jesus Badillo Espinosa');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Jesus Badillo Espinosa' AND m.nombre = 'Tecnologías de Información Emergente' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Seguridad Computacional', 1);
INSERT INTO Docente (nombre) VALUES ('Sergio Rueda Durán');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Sergio Rueda Durán' AND m.nombre = 'Seguridad Computacional' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Ingeniería de Redes II', 1);
INSERT INTO Docente (nombre) VALUES ('David Garcia del Valle');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'David Garcia del Valle' AND m.nombre = 'Ingeniería de Redes II' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Inteligencia Artificial', 1);
INSERT INTO Docente (nombre) VALUES ('Fátima Margarita Lechuga Blanco');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Fátima Margarita Lechuga Blanco' AND m.nombre = 'Inteligencia Artificial' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Auditoría y Consultoría Informática', 1);
INSERT INTO Docente (nombre) VALUES ('Roberto Uribe Flores');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Roberto Uribe Flores' AND m.nombre = 'Auditoría y Consultoría Informática' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Maria Antonieta Valencia Castro' AND m.nombre = 'Desarrollo Humano' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Docente (nombre) VALUES ('José Luis Vargas Lagunas');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'José Luis Vargas Lagunas' AND m.nombre = 'Adiestramiento militar y capacitación docente I' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Ingeniería Ambiental', 1);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'German Dimitriv Jojoa Unigarro' AND m.nombre = 'Ingeniería Ambiental' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Costos aplicados a la ingeniería', 1);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Ricardo Alejandro Juárez Ruiz' AND m.nombre = 'Costos aplicados a la ingeniería' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Microprocesadores y microcontroladores', 1);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Roberto Uribe Flores' AND m.nombre = 'Microprocesadores y microcontroladores' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Sistemas distribuidos', 1);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Fátima Margarita Lechuga Blanco' AND m.nombre = 'Sistemas distribuidos' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Técnicas de producción de sistemas', 1);
INSERT INTO Docente (nombre) VALUES ('Yosafat Moscoso Malagon');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Yosafat Moscoso Malagon' AND m.nombre = 'Técnicas de producción de sistemas' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Bases de datos avanzadas', 1);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Amparo Isabeth Villa García' AND m.nombre = 'Bases de datos avanzadas' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Diseño de compiladores', 1);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'María Teresa Parra Velasco' AND m.nombre = 'Diseño de compiladores' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Maria Antonieta Valencia Castro' AND m.nombre = 'Desarrollo Humano' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'José Luis Vargas Lagunas' AND m.nombre = 'Adiestramiento militar y capacitación docente I' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Rafael Juárez Vargas' AND m.nombre = 'Ingeniería ambiental' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Ricardo Alejandro Juárez Ruiz' AND m.nombre = 'Costos aplicados a la ingeniería' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Docente (nombre) VALUES ('Yukio Rosales Luengas');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Yukio Rosales Luengas' AND m.nombre = 'Microprocesadores y microcontroladores' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Fátima Margarita Lechuga Blanco' AND m.nombre = 'Sistemas distribuidos' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Yosafat Moscoso Malagon' AND m.nombre = 'Técnicas de producción de sistemas' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Amparo Isabeth Villa García' AND m.nombre = 'Bases de datos avanzadas' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'María Teresa Parra Velasco' AND m.nombre = 'Diseño de compiladores' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Maria Antonieta Valencia Castro' AND m.nombre = 'Desarrollo Humano' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Cultura de la Calidad', 1);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Juan David Ramírez Durán' AND m.nombre = 'Cultura de la Calidad' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Investigación de Operaciones I', 1);
INSERT INTO Docente (nombre) VALUES ('Ulises Adair Hernández Hurtado');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Ulises Adair Hernández Hurtado' AND m.nombre = 'Investigación de Operaciones I' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Matemáticas Computacionales', 1);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Berenice Borja Benítez' AND m.nombre = 'Matemáticas Computacionales' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Lenguaje Ensamblador', 1);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Edmanuel Rangel de la Cruz' AND m.nombre = 'Lenguaje Ensamblador' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Lenguajes de Programación', 1);
INSERT INTO Docente (nombre) VALUES ('Pedro David Filio Aguilar');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Pedro David Filio Aguilar' AND m.nombre = 'Lenguajes de Programación' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Arquitectura de Computadoras II', 1);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Yukio Rosales Luengas' AND m.nombre = 'Arquitectura de Computadoras II' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Maria Antonieta Valencia Castro' AND m.nombre = 'Desarrollo Humano' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Filosofía', 1);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Luisa Fernanda Rojas Paz' AND m.nombre = 'Filosofía' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Ecuaciones diferenciales', 1);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Diego Alfaro Manjarrez' AND m.nombre = 'Ecuaciones diferenciales' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Cálculo vectorial II', 1);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Ulises Adair Hernández Hurtado' AND m.nombre = 'Cálculo vectorial II' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Electricidad y magnetismo', 1);
INSERT INTO Docente (nombre) VALUES ('Raúl Rivera Anaya');
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Raúl Rivera Anaya' AND m.nombre = 'Electricidad y magnetismo' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Programación avanzada', 1);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Yosafat Moscoso Malagon' AND m.nombre = 'Programación avanzada' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Materia (nombre, carrera_id) VALUES ('Organización de computadoras', 1);
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Cristal Karina Galindo Duran' AND m.nombre = 'Organización de computadoras' AND m.carrera_id = 1 LIMIT 1;
INSERT INTO Asignacion (docente_id, materia_id) SELECT d.docente_id, m.materia_id FROM Docente d, Materia m WHERE d.nombre = 'Maria Antonieta Valencia Castro' AND m.nombre = 'Desarrollo Humano' AND m.carrera_id = 1 LIMIT 1;
